"""create accounts

Revision ID: d395b12f93db
Revises: 
Create Date: 2023-01-28 15:48:15.238895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd395b12f93db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=225), nullable=False),
    sa.Column('admin_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_accounts_admin_name'), 'admin_accounts', ['admin_name'], unique=True)
    op.create_index(op.f('ix_admin_accounts_admin_secret'), 'admin_accounts', ['admin_secret'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_account_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(length=225), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['admin_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_account_id', 'external_user_id')
    )
    op.create_index(op.f('ix_accounts_external_user_id'), 'accounts', ['external_user_id'], unique=True)
    op.create_index(op.f('ix_accounts_school_id'), 'accounts', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_school_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_admin_accounts_admin_secret'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_admin_name'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
