version: '3'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: cale
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cale_development
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
