name: actionlint
on: push
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Chekout
        uses: actions/checkout@v3
      - name: Install actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run actionlint
        shell: bash
        run: ./actionlint -color
