name: workflow
on: push
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Chekout
        uses: actions/checkout@v3
      - name: Install actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run actionlint
        shell: bash
        run: ./actionlint -color
  lint:
    runs-on: ubuntu-latest
    needs: actionlint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
      - name: Python Version
        run: python -V
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      - name: Poetry Version
        run: poetry --version
      - name: Install Dependencies
        run: poetry install --only main,dev --no-root --no-interaction
      - name: Run black
        run: poetry run black --check .
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run mypy
        run: poetry run mypy .
